Use tmpfs if devtmpfs is not available
This makes the ramdisk always mount some kind of /dev,
and then try to move it to the new root.
This unbreaks handling of nodes created pre-udev likefor example lvm does.

diff --git a/defaults/linuxrc b/defaults/linuxrc
--- a/defaults/linuxrc
+++ b/defaults/linuxrc
@@ -727,11 +727,11 @@ echo -ne "${BOLD}.${NORMAL}"
 
 # If devtmpfs is mounted, try move it to the new root
 # If that fails, try to unmount all possible mounts of devtmpfs as stuff breaks otherwise
-if grep -qs devtmpfs /proc/mounts
+if grep -qs "/dev " /proc/mounts
 then
 	if ! mount --move /dev "${CHROOT}"/dev
 	then
-		umount -t devtmpfs || echo '*: Failed to move and unmount the devtmpfs /dev!'
+		umount /dev || echo '*: Failed to move and unmount the ramdisk /dev!'
 	fi
 fi
 
