New release:
  *  Busybox patched to support loops on 2.4 thus giving 2.4 squashfs
     support.
  *  Various bug fixes; #46167, #46278, #47551, #48219, #48308,
     #48339, #49728, #51395, #51948.
  *  Speedups: "" > ''; [ ! ... ] && > [ ... ] || et al where
     applicable.


git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@106 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -8,18 +8,18 @@
 
 USE_DEVFS_NORMAL=1
 
-if [ "$$" != "1" ]
+if [ "$$" != '1' ]
 then
-	echo "/linuxrc has to be run as the init process as the one"
-	echo "with a PID of 1. Try adding init=\"/linuxrc\" to the"
-	echo "kernel command line or running 'exec /linuxrc'."
+	echo '/linuxrc has to be run as the init process as the one'
+	echo 'with a PID of 1. Try adding init="/linuxrc" to the'
+	echo 'kernel command line or running "exec /linuxrc".'
 	exit 1
 fi
 
 mount -o remount,rw /
 mount -t proc proc /proc
 
-[ -n "$QUIET" ] && echo "0" > /proc/sys/kernel/printk
+[ -n "$QUIET" ] && echo '0' > /proc/sys/kernel/printk
 
 CMDLINE=`cat /proc/cmdline`
 # Scan CMDLINE for any specified real_root= or cdroot arguments
@@ -31,7 +31,7 @@ do
 		;;
 		cdroot)
 			CDROOT=1
-			REAL_ROOT=""
+			REAL_ROOT=''
 		;;
 		devfs)
 			USE_DEVFS_NORMAL=1
@@ -65,7 +65,7 @@ do
 	done
 done
 
-if [ -d "/lib/modules" ]
+if [ -d '/lib/modules' ]
 then
 	echo -e "${GOOD}>>${NORMAL}${BOLD} Loading modules...${NORMAL}"
 	# Load appropriate kernel modules
@@ -81,12 +81,12 @@ fi
 chooseKeymap() {
 	echo -e "${GOOD}>>${NORMAL}${BOLD} Loading keymaps...${NORMAL}"
 	cat /lib/keymaps/keymapList
-	read -p "<< Load keymap: " keymap
+	read -p '<< Load keymap: ' keymap
 	if [ -e /lib/keymaps/${keymap}.map ]
 	then
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Loading the ''${keymap}'' keymap...${NORMAL}"
 		loadkmap < /lib/keymaps/${keymap}.map
-	elif [ "$keymap" = "" ]
+	elif [ "$keymap" = '' ]
 	then
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Loading default US keymap...${NORMAL}"
 		loadkmap < /lib/keymaps/us.map
@@ -104,7 +104,7 @@ fi
 echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting filesystems...${NORMAL}"
 
 mkdir /newroot
-if [ "${CDROOT}" -eq "1" ]
+if [ "${CDROOT}" -eq '1' ]
 then
 	mount -t tmpfs tmpfs /newroot
 	mkdir /newroot/dev /newroot/mnt /newroot/mnt/cdrom /newroot/mnt/livecd /newroot/tmp /newroot/tmp/.initrd /newroot/mnt/gentoo
@@ -114,16 +114,16 @@ then
 
 	findcdmount /newroot/dev/cdroms/*
 	# not in /dev/cdroms try /dev/ide/cd
-	if [ "${REAL_ROOT}" = "" ]
+	if [ "${REAL_ROOT}" = '' ]
 	then
 		findcdmount /newroot/dev/ide/cd/*
 	fi
 
-	if [ "${REAL_ROOT}" = "" ]
+	if [ "${REAL_ROOT}" = '' ]
 	then
 		exec /bin/ash
 
-		# Undo stuff		
+		# Undo stuff	
 		# kill_devfsd # We run devfsd with -np now
 		sleep 1
 		umount /newroot/dev/
@@ -137,32 +137,42 @@ then
 fi
 
 # Don't do else b/c we set CDROOT=0 if it fails to detect
-if [ "${CDROOT}" -eq "0" -a "${USE_DEVFS_NORMAL}" -eq "1" ]
+if [ "${CDROOT}" -eq '0' -a "${USE_DEVFS_NORMAL}" -eq '1' ]
 then
 	[ ! -e /dev/.devfsd ] && mount -t devfs devfs /dev
 	devfsd /dev -np
+fi
+
+if [ "${DO_lvm2}" ]
+then
+	if [ -e '/sbin/vgscan' -a -e '/sbin/vgchange' ]
+	then
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Scanning for Volume Groups...${NORMAL}"
+		/sbin/vgscan
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Activating Volume Groups...${NORMAL}"
+		/sbin/vgchange -ay
+	fi
 fi
 
 echo -e "${GOOD}>>${NORMAL}${BOLD} Determining root device...${NORMAL}"
 
 while true
 do
-	while [ "${got_good_root}" != "1" ]
+	while [ "${got_good_root}" != '1' ]
 	do
-		
-		if [ "${REAL_ROOT}" = "shell" ]
+		if [ "${REAL_ROOT}" = 'shell' ]
 		then
 			/bin/ash
 
-			REAL_ROOT=""
+			REAL_ROOT=''
 			got_good_root=0
 			continue
-		elif [ "${REAL_ROOT}" = "" ]
+		elif [ "${REAL_ROOT}" = '' ]
 		then
 			# No REAL_ROOT determined/specified. Prompt user for root block device.
 			echo -e "${BAD}>>${NORMAL} The root block device is unspecified or not detected."
-			echo "   Please specify a device to boot, or \"shell\" for a shell."
-			echo -n "boot() :: "
+			echo '   Please specify a device to boot, or "shell" for a shell...'
+			echo -n 'boot() :: '
 			read REAL_ROOT
 			got_good_root=0
 		elif [ -b "${REAL_ROOT}" ]
@@ -175,62 +185,62 @@ do
 		fi
 	done
 
-	if [ "${CDROOT}" -eq "1" -a "${got_good_root}" = "1" ]
+	if [ "${CDROOT}" -eq '1' -a "${got_good_root}" = '1' ]
 	then
 		break
 	else
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting root...${NORMAL}"
 
 		mount -o rw ${REAL_ROOT} /newroot
-		if [ "$?" = "0" ]
+		if [ "$?" = '0' ]
 		then
 			break
 		else
 			echo -e "${BAD}>> ${NORMAL}Could not mount specified ROOT, try again"
 			got_good_root=0
-			REAL_ROOT=""
+			REAL_ROOT=''
 		fi
 	fi
 done
 
-[ -n "$QUIET" ] && echo "6" > /proc/sys/kernel/printk
+[ -n "$QUIET" ] && echo '6' > /proc/sys/kernel/printk
 check_loop() {
-	if [ "${LOOP}" = "" -o ! -e "mnt/cdrom/${LOOP}" ]
+	if [ "${LOOP}" = '' -o ! -e "mnt/cdrom/${LOOP}" ]
 	then
 		echo "Invalid loop location: ${LOOP}"
-		echo "Please export LOOP with a valid location, or reboot and pass a proper loop=..."
-		echo "kernel command line!"
+		echo 'Please export LOOP with a valid location, or reboot and pass a proper loop=...'
+		echo 'kernel command line!'
 		/bin/ash
 	fi
 }
 
-if [ "${CDROOT}" = "1" ]
+if [ "${CDROOT}" = '1' ]
 then
 	echo -e "${GOOD}>>${NORMAL}${BOLD} Filling tmpfs...${NORMAL}"
 	cd /newroot
 
-	# Failsafe if some idiot didn't set loop type
-	if [ "${LOOPTYPE}" = "" ]
+	# Failsafe the loop type wasn't set
+	if [ "${LOOPTYPE}" = '' ]
 	then
 		echo -e "${WARN}** ${NORMAL}${BOLD}Warning: loop type unspecified!${NORMAL}"
-		if [ "${LOOP}" = "/livecd.loop" ]
+		if [ "${LOOP}" = '/livecd.loop' ]
 		then
-			LOOPTYPE="normal"
-		elif [ "${LOOP}" = "/zisofs" ]
+			LOOPTYPE='normal'
+		elif [ "${LOOP}" = '/zisofs' ]
 		then
-			LOOPTYPE="zisofs"
-		elif [ "${LOOP}" = "/livecd.squashfs" ]
+			LOOPTYPE='zisofs'
+		elif [ "${LOOP}" = '/livecd.squashfs' ]
 		then
-			LOOPTYPE="squashfs"
-		elif [ "${LOOP}" = "/livecd.gcloop" ]
+			LOOPTYPE='squashfs'
+		elif [ "${LOOP}" = '/livecd.gcloop' ]
 		then
-			LOOPTYPE="gcloop"
+			LOOPTYPE='gcloop'
 		else
-			LOOPTYPE="noloop"
+			LOOPTYPE='noloop'
 		fi
 	fi
 
-	if [ "${LOOPTYPE}" != "noloop" ]
+	if [ "${LOOPTYPE}" != 'noloop' ]
 	then
 	    check_loop
 	    if [ "${DO_cache}" ]
@@ -243,56 +253,56 @@ then
 			rm -rf /newroot/mnt/livecd.* 2>/dev/null
 			rm -rf /newroot/mnt/zisofs 2>/dev/null
 		else
-			LOOPEXT="../"
+			LOOPEXT='../'
 		fi
 	    fi
 	fi
 
-	if [ "${LOOPTYPE}" = "normal" ]
+	if [ "${LOOPTYPE}" = 'normal' ]
 	then
 		# bind-mount /dev/ so that loop devices can be found
 		mount -o bind /newroot/dev /dev
 
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting loop filesystem...${NORMAL}"
 		mount -t ext2 -o loop,ro /newroot/mnt/cdrom/${LOOPEXT}${LOOP} /newroot/mnt/livecd
-		if [ "$?" != "0" ]
+		if [ "$?" != '0' ]
 		then
-			echo "FAILED TO MOUNT LOOP FILESYSTEM, barfing out to shell"
+			echo 'Failed to mount filesystem; failing back to the shell...'
 			/bin/ash
 		fi
-		FS_LOCATION="mnt/livecd"
+		FS_LOCATION='mnt/livecd'
 		umount /dev
-	elif [ "${LOOPTYPE}" = "squashfs" ]
+	elif [ "${LOOPTYPE}" = 'squashfs' ]
 	then
 		mount -o bind /newroot/dev /dev
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting squashfs filesystem...${NORMAL}"
 		mount -t squashfs -o loop,ro /newroot/mnt/cdrom/${LOOPEXT}${LOOP} /newroot/mnt/livecd
-		if [ "$?" != "0" ]
+		if [ "$?" != '0' ]
 		then
-			echo "FAILED TO MOUNT LOOP FILESYSTEM, barfing out to shell"
+			echo 'Failed to mount filesystem; failing back to the shell...'
 			/bin/ash
 		fi
-		FS_LOCATION="mnt/livecd"
+		FS_LOCATION='mnt/livecd'
 		umount /dev
-	elif [ "${LOOPTYPE}" = "gcloop" ]
+	elif [ "${LOOPTYPE}" = 'gcloop' ]
 	then
 		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting gcloop filesystem...${NORMAL}"
 		mount -o bind /newroot/dev /dev
-		echo " " | losetup -E 19 -e ucl-0 -p0 /newroot/dev/loop0 /newroot/mnt/cdrom/${LOOPEXT}${LOOP}
-		if [ "$?" != "0" ]
+		echo ' ' | losetup -E 19 -e ucl-0 -p0 /newroot/dev/loop0 /newroot/mnt/cdrom/${LOOPEXT}${LOOP}
+		if [ "$?" != '0' ]
 		then
 			echo "FAILED TO losetup THE LOOP DEVICE"
 			/bin/ash
 		fi
 		mount -t ext2 -o ro /newroot/dev/loop0 /newroot/mnt/livecd
-		FS_LOCATION="mnt/livecd"
+		FS_LOCATION='mnt/livecd'
 		umount /dev
-	elif [ "${LOOPTYPE}" = "zisofs" ]
+	elif [ "${LOOPTYPE}" = 'zisofs' ]
 	then
 		FS_LOCATION="mnt/cdrom/${LOOPEXT}${LOOP}"
-	elif [ "${LOOPTYPE}" = "noloop" ]
+	elif [ "${LOOPTYPE}" = 'noloop' ]
 	then
-		FS_LOCATION="mnt/cdrom"
+		FS_LOCATION='mnt/cdrom'
 	fi
 
 	echo -e "${GOOD}>>${NORMAL}${BOLD} Filling filesystem...${NORMAL}"
@@ -314,12 +324,12 @@ cd /newroot
 pivot_root . tmp/.initrd
 echo -n '.'
 
-if [ "${USE_DEVFS_NORMAL}" -eq "1" -a "${CDROOT}" -eq "0" ]
+if [ "${USE_DEVFS_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
 then
 	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
 	mount -n --move /tmp/.initrd/dev dev || echo '*: Failed to move over the /dev tree!'
 	rm /tmp/.initrd/dev -rf || '*: Failed to remove the initrd /dev!'
-elif [ "${CDROOT}" -eq "1" ]
+elif [ "${CDROOT}" -eq '1' ]
 then
 	# If automount at boot was on with devfs, we'll want to umount it
 	# also umount proc
@@ -344,8 +354,8 @@ exec chroot . /bin/sh <<- EOF
  	exec /sbin/init
 EOF
 
-echo "A fatal error has probably occured since /sbin/init did not"
-echo "boot correctly. Trying to open a shell..."
+echo 'A fatal error has probably occured since /sbin/init did not'
+echo 'boot correctly. Trying to open a shell...'
 echo
 exec /bin/bash
 exec /bin/sh
diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -1,27 +1,26 @@
 #!/bin/bash
 # Genkernel v3
 
-GK_V="3.0.2"
-TEMP="/var/tmp/genkernel"
+GK_V='3.0.2b'
+TEMP='/var/tmp/genkernel'
 
 small_die() {
   echo $1
   exit 1
 }
 
-source /etc/genkernel.conf || small_die "could not read /etc/genkernel.conf"
-source ${GK_BIN}/gen_funcs.sh || small_die "could not read ${GK_BIN}/gen_funcs.sh"
+source /etc/genkernel.conf || small_die "Could not read /etc/genkernel.conf"
+source ${GK_BIN}/gen_funcs.sh || small_die "Could not read ${GK_BIN}/gen_funcs.sh"
 clear_log
-source ${GK_BIN}/gen_cmdline.sh || gen_die "could not read ${GK_BIN}/gen_cmdline.sh"
-source ${GK_BIN}/gen_arch.sh || gen_die "could not read ${GK_BIN}/gen_arch.sh"
-source ${GK_BIN}/gen_determineargs.sh || gen_die "could not read ${GK_BIN}/gen_determineargs.sh"
-source ${GK_BIN}/gen_compile.sh || gen_die "could not read ${GK_BIN}/gen_compile.sh"
-source ${GK_BIN}/gen_configkernel.sh || gen_die "could not read ${GK_BIN}/gen_configkernel.sh"
-source ${GK_BIN}/gen_initrd.sh || gen_die "could not read ${GK_BIN}/gen_initrd.sh"
-source ${GK_BIN}/gen_moddeps.sh || gen_die "could not read ${GK_BIN}/gen_moddeps.sh"
-source ${GK_BIN}/gen_package.sh || gen_die "could not read ${GK_BIN}/gen_package.sh"
+source ${GK_BIN}/gen_cmdline.sh || gen_die "Could not read ${GK_BIN}/gen_cmdline.sh"
+source ${GK_BIN}/gen_arch.sh || gen_die "Could not read ${GK_BIN}/gen_arch.sh"
+source ${GK_BIN}/gen_determineargs.sh || gen_die "Could not read ${GK_BIN}/gen_determineargs.sh"
+source ${GK_BIN}/gen_compile.sh || gen_die "Could not read ${GK_BIN}/gen_compile.sh"
+source ${GK_BIN}/gen_configkernel.sh || gen_die "Could not read ${GK_BIN}/gen_configkernel.sh"
+source ${GK_BIN}/gen_initrd.sh || gen_die "Could not read ${GK_BIN}/gen_initrd.sh"
+source ${GK_BIN}/gen_moddeps.sh || gen_die "Could not read ${GK_BIN}/gen_moddeps.sh"
+source ${GK_BIN}/gen_package.sh || gen_die "Could not read ${GK_BIN}/gen_package.sh"
 
-BUILD_ALL=0
 BUILD_KERNEL=0
 BUILD_INITRD=0
 
@@ -32,7 +31,8 @@ do
 	parse_cmdline $Option
 done
 
-if [ "${BUILD_ALL}" -eq 0 -a "${BUILD_KERNEL}" -eq 0 -a "${BUILD_INITRD}" -eq 0 ]
+# Check if no action is specified...
+if [ "${BUILD_KERNEL}" -eq 0 -a "${BUILD_INITRD}" -eq 0 ]
 then
 	usage
 	exit 1
@@ -44,86 +44,96 @@ NORMAL=${GOOD} print_info 1 "Gentoo Linux Genkernel; Version ${GK_V}${NORMAL}"
 get_official_arch
 
 # Read arch-specific config
-source ${ARCH_CONFIG} || gen_die "could not read ${ARCH_CONFIG}"
-source ${GK_SHARE}/${ARCH}/modules_load || gen_die "could not read ${GK_SHARE}/${ARCH}/modules_load"
+source ${ARCH_CONFIG} || gen_die "Could not read ${ARCH_CONFIG}"
+source ${GK_SHARE}/${ARCH}/modules_load || gen_die "Could not read ${GK_SHARE}/${ARCH}/modules_load"
 
 [ ! -f "${TEMP}" ] && mkdir -p "${TEMP}"
 
 # Based on genkernel.conf, arch-specific configs, and commandline options,
-# get the real args for use.
+# get the real arguments for usage...
 determine_real_args
 
 NORMAL=${BOLD} print_info 1 "Compiling Linux Kernel ${BOLD}${KV}${NORMAL} for ${BOLD}${ARCH}${NORMAL}..."
 echo
 
-if ! has_loop
+if [ "${BUILD_INITRD}" -ne '0' ]
 then
-	modprobe loop 2>/dev/null
 	if ! has_loop
 	then
-		print_error 1 "Your kernel does not appear to have loop device support. "
-		print_error 1 "Please load loop support before running genkernel!"
-		gen_die "Load loop support!"
-	else
-		print_info 1 'loop: "loop" module loaded successfully...'
+		modprobe loop 2>/dev/null
+		if ! has_loop
+		then
+			print_error 1 'Your kernel does not appear to have loop device support.'
+			print_error 1 'Please load loop support before running genkernel!'
+			gen_die 'Load loop support!'
+		else
+			print_info 1 'loop: "loop" module loaded successfully...'
+		fi
 	fi
 fi
 
 # Check /boot is mounted
-if ! grep -q "/boot" /proc/mounts
+if ! egrep -q ' /boot ' /proc/mounts
 then
-	if isTrue ${MOUNTBOOT}
+	if egrep -q '^[^#].+	/boot	' /etc/fstab
 	then
-		if ! mount /boot
+		if isTrue ${MOUNTBOOT}
 		then
-			print_warning 1 "${BOLD}WARNING${NORMAL}: Failed to mount /boot!"
-			echo
+			if ! mount /boot
+			then
+				print_warning 1 "${BOLD}WARNING${NORMAL}: Failed to mount /boot!"
+				echo
+			else
+				print_info 1 'mount: /boot mounted successfully!'
+			fi
 		else
-			print_info 1 "mount: /boot mounted successfully!"
+			print_warning 1 "${BOLD}WARNING${NORMAL}: No mounted /boot partition detected!"
+			print_warning 1 '         Run ``mount /boot`` to mount it!'
+			echo
 		fi
-	else
-		print_warning 1 "${BOLD}WARNING${NORMAL}: No mounted /boot partition detected!"
-		print_warning 1 '         Run ``mount /boot`` to mount it!'
-		echo
 	fi
 fi
 
 # Check whether another Genkernel is running
 GENPIDS="`ps -C genkernel --no-headers -o pid | wc -l`"
-if [ "${GENPIDS}" -gt "3" ]
+if [ "${GENPIDS}" -gt '3' ]
 then
-	[ "${GENPIDS}" -gt "4" ] && EX='s'
+	[ "${GENPIDS}" -gt '4' ] && EX='s'
 	print_warning 1 "${BOLD}WARNING${NORMAL}: Another Genkernel instance is running under"
 	print_warning 1 "         process ID${EX} " 0
 	GENPIDS=`ps -C genkernel --no-headers -o pid`
-	echo -n ${GENPIDS} | sed -e "s/$$//; s/ /, /g"
-	echo "halting..."
+	echo -n "${GENPIDS}" | sed -e "s/$$//; s/ /, /g"
+	echo 'halting...'
 	echo
-	print_warning 1 "Running multiple genkernels on the same source tree will cause data loss!"
+	print_warning 1 'Running multiple genkernels on the same source tree will cause data loss!'
 	print_info 1 "Press ^C to halt; ^D to continue [ ${BOLD}if${NORMAL} you know what you're doing! ]"
 	cat
 	echo
-	TEMP="/var/tmp/genkernel-`date | md5sum | cut -d\  -f1`"
-	print_info 1 "thread: Running multiple genkernels may cause problems!"
+	CTEMP="${TEMP}"
+	TEMP="/var/tmp/genkernel-`dd if=/dev/random count=1 2>/dev/null | md5sum | cut -d\  -f1`"
+	print_info 1 'thread: Running multiple genkernels may cause problems!'
 	print_info 1 "thread: Temporary files reallocated to ${TEMP}..."
 	echo
 fi
 
-# Configure kernel
-config_kernel
+if [ ${BUILD_KERNEL} -eq 1 ]
+then
+	# Configure kernel
+	config_kernel
 
-# Make deps
-compile_dep
+	# Make deps
+	compile_dep
 
-# Compile kernel
-compile_kernel
+	# Compile kernel
+	compile_kernel
 
-# Compile modules
-compile_modules
+	# Compile modules
+	compile_modules
 
-print_info 1 "Copying config for successful build to /etc/kernels/kernel-config-${ARCH}-${KV}"
-[ ! -e "/etc/kernels" ] && mkdir -p /etc/kernels
-cp "${KERNEL_DIR}/.config" "/etc/kernels/kernel-config-${ARCH}-${KV}"
+	print_info 1 "Copying config for successful build to /etc/kernels/kernel-config-${ARCH}-${KV}"
+	[ ! -e "/etc/kernels" ] && mkdir -p /etc/kernels
+	cp "${KERNEL_DIR}/.config" "/etc/kernels/kernel-config-${ARCH}-${KV}"
+fi
 
 # Run callback
 if [ "${CMD_CALLBACK}" != "" ]
@@ -156,51 +166,74 @@ then
 	print_info 1 "" 1 0
 fi
 
-# Compile dietlibc
-if [ "${USE_DIETLIBC}" = "1" ]
+if [ "${BUILD_INITRD}" -eq '1' ]
 then
-	compile_dietlibc
-fi
-
-# Compile Busybox
-compile_busybox
-
-# Only compile insmod if we're installing modules onto the initrd
-if [ "${NOINITRDMODULES}" = "" ]
-then
-	if [ "${PAT}" -gt "4" ]
+	# Compile dietlibc
+	if [ "${USE_DIETLIBC}" = '1' ]
 	then
-		# Compile module-init-tools
-		compile_module_init_tools
-	else
-		compile_modutils
+		compile_dietlibc
 	fi
+
+	# Compile Busybox
+	compile_busybox
+
+	# Only compile insmod if we're installing modules onto the initrd
+	if [ "${NOINITRDMODULES}" = '' ]
+	then
+		if [ "${PAT}" -gt '4' ]
+		then
+			# Compile module-init-tools
+			compile_module_init_tools
+		else
+			compile_modutils
+		fi
+	fi
+
+	compile_devfsd
+
+	# Create initrd
+	create_initrd
+else
+	print_info 1 'initrd: Not building since only the kernel was requested...'
 fi
+[ "${MINKERNPACKAGE}" != "" ] && gen_minkernpackage
 
-compile_devfsd
+# Clean up...
+[ -n "${CTEMP}" ] && rm -rf "${TEMP}"
 
-# Create initrd
-create_initrd
-
-if [ "${MINKERNPACKAGE}" != "" ]
+if [ "${BUILD_KERNEL}" -eq '1' ]
 then
-	gen_minkernpackage
+	print_info 1 ''
+	print_info 1 "Kernel compiled successfully!"
+	print_info 1 ''
+	print_info 1 'Required Kernel Parameters:'
+	if [ "${BUILD_INITRD}" -eq '0' ]
+	then
+		print_info 1 '    root=/dev/$ROOT'
+		print_info 1 '    [ And "vga=0x317 splash=verbose" if you use a framebuffer ]'
+		print_info 1 ''
+		print_info 1 '    Where $ROOT is the device node for your root partition as the'
+		print_info 1 '    one specified in /etc/fstab'
+	else	
+		print_info 1 '    root=/dev/ram0 real_root=/dev/$ROOT init=/linuxrc'
+		[ "${INITRD_SIZE}" -ge 4096 ] && print_info 1 "    ramdisk=8192"
+		print_info 1 '    [ And "vga=0x317 splash=verbose" if you use a framebuffer ]'
+		print_info 1 ''
+		print_info 1 '    Where $ROOT is the device node for your root partition as the'
+		print_info 1 '    one specified in /etc/fstab'
+		print_info 1 ''
+		print_info 1 "If you require Genkernel's hardware detection features; you MUST"
+		print_info 1 'tell your bootloader to use the provided initrd file. Otherwise;'
+		print_info 1 'substitute the root argument for the real_root argument if you are'
+		print_info 1 'not planning to use the initrd...'
+	fi
+else
+	print_info 1 ''
+	print_info 1 'initrd compiled successfully!'
 fi
 
 print_info 1 ''
-print_info 1 "Kernel compiled successfully!"
+print_info 1 'Do NOT report kernel bugs as genkernel bugs unless your bug'
+print_info 1 'is about the default genkernel configuration...'
 print_info 1 ''
-print_info 1 "Required Kernel Parameters:"
-print_info 1 '    root=/dev/ram0 real_root=/dev/$ROOT init=/linuxrc'
-[ "${INITRD_SIZE}" -gt 4096 ] && print_info 1 "    ramdisk_size=${INITRD_SIZE}"
-print_info 1 '    [ And "vga=0x317 splash=verbose" if you use a framebuffer ]'
-print_info 1 ''
-print_info 1 '    Where $ROOT is the device node for your root partition as the'
-print_info 1 '    one specified in /etc/fstab'
-print_info 1 ''
-print_info 1 "You MUST also tell your bootloader to use the generated initrd."
-print_info 1 ''
-print_info 1 "Do NOT report kernel bugs (configs included) as genkernel bugs."
-print_info 1 "Make sure you have the latest genkernel before reporting bugs."
-print_info 1 ""
-print_info 1 "For more information please see /usr/share/genkernel/README..."
+print_info 1 'Make sure you have the latest genkernel before reporting bugs.'
