Bugfixes for bugs #46941, #46641; and a cosmetic fix for LiveCD mount issues.
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@104 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -326,6 +326,8 @@ then
 	mount -t proc proc /proc
 	umount /tmp/.initrd/proc > /dev/null 2>&1 || echo "*: Failed to unmount /tmp/.initrd/proc!"
 	umount /dev > /dev/null 2>&1
+	mount -n --move /tmp/.initrd/dev dev || echo '*: Failed to move over the /dev tree!'
+	rm /tmp/.initrd/dev -rf || '*: Failed to remove the initrd /dev!'
 	umount /proc > /dev/null 2>&1
 fi
 echo -n '.'
