Version bump. Closes bugs #34948, #37371, #41129, #41166, #42725, #42815, #44127, #44556, and #44601.
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@98 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -8,13 +8,19 @@
 
 USE_DEVFS_NORMAL=1
 
+if [ "$$" != "1" ]
+then
+	echo "/linuxrc has to be run as the init process as the one"
+	echo "with a PID of 1. Try adding init=\"/linuxrc\" to the"
+	echo "kernel command line or running 'exec /linuxrc'."
+	exit 1
+fi
+
 mount -o remount,rw /
-mount /proc
+mount -t proc proc /proc
 
 [ -n "$QUIET" ] && echo "0" > /proc/sys/kernel/printk
 
-echo "${GOOD} Gentoo initrd startup..."
-echo "STEP 1: Command-line parsing"
 CMDLINE=`cat /proc/cmdline`
 # Scan CMDLINE for any specified real_root= or cdroot arguments
 for x in ${CMDLINE}
@@ -61,17 +67,41 @@ done
 
 if [ -d "/lib/modules" ]
 then
-	echo "STEP 2: Module loading"
+	echo -e "${GOOD}>>${NORMAL}${BOLD} Loading modules...${NORMAL}"
 	# Load appropriate kernel modules
-	for x in $MY_HWOPTS
+	for modules in $MY_HWOPTS
 	do
-		modules_scan $x
+		modules_scan $modules
+		eval DO_`echo $modules | sed 's/-//'`=1
 	done
 else
-	echo "STEP 2: Skipping module load. No modules in initrd"
+	echo -e "${GREEN}>>${NORMAL}${BOLD} Skipping module load; no modules in the initrd!${NORMAL}"
 fi
 
-echo "STEP 3: Mounting necessary filesystems per boot options"
+chooseKeymap() {
+	echo -e "${GOOD}>>${NORMAL}${BOLD} Loading keymaps...${NORMAL}"
+	cat /lib/keymaps/keymapList
+	read -p "<< Load keymap: " keymap
+	if [ -e /lib/keymaps/${keymap}.map ]
+	then
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Loading the ''${keymap}'' keymap...${NORMAL}"
+		loadkmap < /lib/keymaps/${keymap}.map
+	elif [ "$keymap" = "" ]
+	then
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Loading default US keymap...${NORMAL}"
+		loadkmap < /lib/keymaps/us.map
+	else
+		echo -e "${BAD}!! ${NORMAL}${BOLD}Sorry, but keymap ''${keymap}'' is invalid!${NORMAL}"
+		chooseKeymap
+	fi
+}
+
+if [ "${DO_keymap}" ]
+then
+	chooseKeymap
+fi
+
+echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting filesystems...${NORMAL}"
 
 mkdir /newroot
 if [ "${CDROOT}" -eq "1" ]
@@ -89,10 +119,8 @@ then
 		findcdmount /newroot/dev/ide/cd/*
 	fi
 
-
 	if [ "${REAL_ROOT}" = "" ]
 	then
-		echo "Dropping to shell so you can fix your shit"
 		exec /bin/ash
 
 		# Undo stuff		
@@ -115,7 +143,7 @@ then
 	devfsd /dev -np
 fi
 
-echo "STEP 4: Determining root device"
+echo -e "${GOOD}>>${NORMAL}${BOLD} Determining root device...${NORMAL}"
 
 while true
 do
@@ -126,40 +154,39 @@ do
 		then
 			/bin/ash
 
-			#set REAL_ROOT to "" so we get a prompt for the real root after the shell exits.
 			REAL_ROOT=""
 			got_good_root=0
 			continue
 		elif [ "${REAL_ROOT}" = "" ]
 		then
-			#no REAL_ROOT determined/specified. Prompt user for root block device.
-			echo "Root block device unspecified or not detected."
-			echo "Please specify a device to boot, or \"shell\" for a shell."
-			echo -n ": "
+			# No REAL_ROOT determined/specified. Prompt user for root block device.
+			echo -e "${BAD}>>${NORMAL} The root block device is unspecified or not detected."
+			echo "   Please specify a device to boot, or \"shell\" for a shell."
+			echo -n "boot() :: "
 			read REAL_ROOT
 			got_good_root=0
 		elif [ -b "${REAL_ROOT}" ]
 		then
 			got_good_root=1
 		else
+			echo -e "${BAD}>>${NORMAL} Block device ${REAL_ROOT} is not a valid root device..."
 			REAL_ROOT=""
 			got_good_root=0
 		fi
 	done
 
-
 	if [ "${CDROOT}" -eq "1" -a "${got_good_root}" = "1" ]
 	then
 		break
 	else
-		echo "STEP 4a: Mounting root"
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting root...${NORMAL}"
 
 		mount -o rw ${REAL_ROOT} /newroot
 		if [ "$?" = "0" ]
 		then
 			break
 		else
-			echo "Could not mount specified ROOT, try again"
+			echo -e "${BAD}>> ${NORMAL}Could not mount specified ROOT, try again"
 			got_good_root=0
 			REAL_ROOT=""
 		fi
@@ -167,27 +194,25 @@ do
 done
 
 [ -n "$QUIET" ] && echo "6" > /proc/sys/kernel/printk
-echo "STEP 5: Finishing up"
-
 check_loop() {
 	if [ "${LOOP}" = "" -o ! -e "mnt/cdrom/${LOOP}" ]
 	then
 		echo "Invalid loop location: ${LOOP}"
-		echo "please export LOOP with a valid location, or reboot and pass a proper loop="
-		echo "kernel command line"
+		echo "Please export LOOP with a valid location, or reboot and pass a proper loop=..."
+		echo "kernel command line!"
 		/bin/ash
 	fi
 }
 
 if [ "${CDROOT}" = "1" ]
 then
-	echo "STEP 5a: filling tmpfs filesystem"
+	echo -e "${GOOD}>>${NORMAL}${BOLD} Filling tmpfs...${NORMAL}"
 	cd /newroot
 
 	# Failsafe if some idiot didn't set loop type
 	if [ "${LOOPTYPE}" = "" ]
 	then
-		echo "YOU FORGOT TO SPECIFY LOOPTYPE TRYING TO AUTODETECT"
+		echo -e "${WARN}** ${NORMAL}${BOLD}Warning: loop type unspecified!${NORMAL}"
 		if [ "${LOOP}" = "/livecd.loop" ]
 		then
 			LOOPTYPE="normal"
@@ -203,7 +228,6 @@ then
 		else
 			LOOPTYPE="noloop"
 		fi
-		echo "DETECTED LOOPTYPE: $LOOPTYPE"
 	fi
 
 	if [ "${LOOPTYPE}" = "normal" ]
@@ -213,7 +237,7 @@ then
 		# bind-mount /dev/ so that loop devices can be found
 		mount -o bind /newroot/dev /dev
 
-		echo "STEP 5a1: mounting loop filesystem"
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting loop filesystem...${NORMAL}"
 		mount -t ext2 -o loop,ro /newroot/mnt/cdrom/${LOOP} /newroot/mnt/livecd
 		if [ "$?" != "0" ]
 		then
@@ -226,7 +250,7 @@ then
 	then
 		check_loop
 		mount -o bind /newroot/dev /dev
-		echo "STEP 5a1: mounting squashfs filesystem"
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting squashfs filesystem...${NORMAL}"
 		mount -t squashfs -o loop,ro /newroot/mnt/cdrom/${LOOP} /newroot/mnt/livecd
 		if [ "$?" != "0" ]
 		then
@@ -238,8 +262,8 @@ then
 	elif [ "${LOOPTYPE}" = "gcloop" ]
 	then
 		check_loop
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Mounting gcloop filesystem...${NORMAL}"
 		mount -o bind /newroot/dev /dev
-		echo "STEP 5a1: mounting gcloop (ext2) filesystem"
 		echo " " | losetup -E 19 -e ucl-0 -p0 /newroot/dev/loop0 /newroot/mnt/cdrom/${LOOP}
 		if [ "$?" != "0" ]
 		then
@@ -258,7 +282,7 @@ then
 		FS_LOCATION="mnt/cdrom"
 	fi
 
-	echo "STEP 5a2: filling filesystem"
+	echo "${GOOD}>>${NORMAL}${BOLD} Filling filesystem...${NORMAL}"
 	for x in ${ROOT_LINKS}
 	do
 		ln -s "${FS_LOCATION}/${x}" "${x}"
@@ -267,63 +291,47 @@ then
 	chmod 1777 tmp
 	(cd /newroot/${FS_LOCATION}; cp -a ${ROOT_TREES} /newroot)
 else
-	echo "STEP 5b: setting up stuff for pivot_root"
 	mkdir -p /newroot/tmp/.initrd
 fi
 
-echo "STEP 5c: redirect console"
-console=/newroot/dev/console
-[ ! -e "$console" ] && mknod $console c 5 1
-exec < $console > $console 2>&1 || echo "CONSOLE REDIRECTION FAILED, /dev ON ROOT DOES NOT CONTAIN console !!!"
-
-echo "STEP 6: pivot_root and exec/chroot real init"
-
+[ ! -e /newroot/dev/console ] && mknod /newroot/dev/console c 5 1
+echo -ne "${GOOD}>>${NORMAL}${BOLD} Booting"
 
 cd /newroot
 pivot_root . tmp/.initrd
+echo -n '.'
 
 if [ "${USE_DEVFS_NORMAL}" -eq "1" -a "${CDROOT}" -eq "0" ]
 then
-	# must mount a new devfs before we can
-	# umount the old one for some reason
-	mount -t proc proc /proc
-	mount -t devfs devfs /dev
-	umount /tmp/.initrd/proc || echo "COULD NOT UMOUNT tmp/.initrd/proc !!!"
-	umount /tmp/.initrd/dev || echo "COULD NOT UMOUNT tmp/.initrd/dev !!!"
-
-	# at this point it lets us umount the new
-	# devfs, don't know why, just does, stop
-	# asking questions!
-	umount /dev
-	umount /proc
-	cp -f /etc/mtab /etc/mtab.initrd-here > /dev/null 2>&1
-
+	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
+	mount -n --move /tmp/.initrd/dev dev || echo '*: Failed to move over the /dev tree!'
+	rm /tmp/.initrd/dev -rf || '*: Failed to remove the initrd /dev!'
 elif [ "${CDROOT}" -eq "1" ]
 then
 	# If automount at boot was on with devfs, we'll want to umount it
 	# also umount proc
-	echo "STEP 6a: clean up mounts"
 	mount -t proc proc /proc
-	umount /tmp/.initrd/proc > /dev/null 2>&1 || echo "COULD NOT UMOUNT /tmp/.initrd/proc !!!"
+	umount /tmp/.initrd/proc > /dev/null 2>&1 || echo "*: Failed to unmount /tmp/.initrd/proc!"
 	umount /dev > /dev/null 2>&1
 	umount /proc > /dev/null 2>&1
 fi
+echo -n '.'
 
 # /usr/src/linux/Documentation/initrd.txt 
 # here's the line it says we should do:
 #       exec chroot . /sbin/init </dev/console >/dev/console 2>&1
 
+exec <dev/console >dev/console 2>&1
+echo '.'
 exec chroot . /bin/sh <<- EOF
-	umount /tmp/.initrd || echo "UMOUNT of /tmp/.initrd FAILED!!!" && /sbin/blockdev --flushbufs /dev/ram0
-	echo "INIT: starting /sbin/init ${CMDLINE}"
-	exec /sbin/init ${CMDLINE}
+ 	umount /tmp/.initrd || echo "*: Failed to unmount the initrd!"
+	/sbin/blockdev --flushbufs /dev/ram0 >/dev/null 2>&1
+ 	exec /sbin/init
 EOF
 
-# exec chroot . /sbin/init ${CMDLINE} < /dev/console > /dev/console 2>&1
-echo "IF YOU ARE SEEING THIS MESSAGE, A FATAL ERROR HAS OCCURRED"
-echo "MOST LIKELY /sbin/init DOES NOT EXIST, ATTEMPTING TO DROP"
-echo "YOU TO A SHELL"
-
+echo "A fatal error has probably occured since /sbin/init did not"
+echo "boot correctly. Trying to open a shell..."
+echo
 exec /bin/bash
 exec /bin/sh
 exec /bin/ash
diff --git a/generic/modprobe b/generic/modprobe
--- a/generic/modprobe
+++ b/generic/modprobe
@@ -1,36 +1,23 @@
 #!/bin/ash
 
-#KV=`uname -r`
-#KMAJOR=`echo ${KV} | cut -d. -f1`
-#KMINOR=`echo ${KV} | cut -d. -f2`
-#INSMOD="insmod.static"
-
-#if [ "${KMINOR}" -gt "4" ]
-#then
-#	KEXT=".ko"
-#else
-#	KEXT=".o"
-#fi
-
 . /etc/initrd.defaults
 
 usage()
 {
-	echo "modprobe gentoo script v1.0"
 	echo "Usage:"
 	echo "  modprobe moduleprefix"
-	echo ""
+	echo
 	echo "Ex:"
 	echo "  modprobe eepro100"
-	echo ""
-	echo "Note: Do not pass the suffix to modprobe"
+	echo
+	echo "Note: Do not pass the suffix to modprobe!"
 	exit 1
 }
 
 # Pass module name to this function
 modules_dep_list()
 {
-	if [ "$#" != "1" ]
+	if [ "$#" -lt "1" ]
 	then
 		echo "modules_dep_list(): improper usage"
 		exit 1
@@ -91,7 +78,10 @@ modprobe2()
 	local modlist
 	local ret
 
-	if [ "$#" != "1" ]
+	local echoAppend
+	local echoFlags
+
+	if [ "$#" -lt "1" ]
 	then
 		echo "modprobe(): improper usage"
 		exit 1
@@ -99,8 +89,8 @@ modprobe2()
 	real_path=`real_mod_path ${1}`
 	if [ "${real_path}" = "" -o "${real_path}" = " " ]
 	then
-		echo "no such module found"
-		exit 1
+		echo "module not found..."
+		exit 2
 	fi
 	modlist=`modules_dep_list ${1}`
 	if [ "${modlist}" != "" -a "${modlist}" != " " ]
@@ -109,7 +99,6 @@ modprobe2()
 	else
 		deps=""
 	fi
-#	echo "$1 -- DEPS='${deps}'"
 	# Make sure we don't do any endless loops!
 
 	LOADED_MODULES="${LOADED_MODULES} ${1}"
@@ -119,30 +108,30 @@ modprobe2()
 		then
 			if [ "${x}" != "" -a "${x}" != " " ]
 			then
-#				echo "loading dep: ${x}"
-				modprobe2 "${x}"
+				modprobe2 "${x}" -n
 			fi
 		else
 			filler=1
-#			echo "skipping ${x}, module already loaded by us"
 		fi
 	done
-#	echo "running insmod on '${real_path}'"
 	${INSMOD} ${real_path} > /dev/null 2>&1
 	ret=$?
 	if [ "$ret" -eq "0" ]
 	then
-		echo "module ${real_path} loaded"
+		echoAppend=" loaded..."
+		[ "${2}" = "-n" ] && echoFlags="-n" && echoAppend=", "
+		echo ${echoFlags} "${1}${echoAppend}"
 	fi
 	return $ret
 }
 
 
-if [ "$#" != "1" ]
+if [ "$#" -lt "1" ]
 then
 	usage
 fi
 
+[ -f "/modules.cache" ] || touch /modules.cache
 for x in `cat /modules.cache`
 do
 	LOADED_MODULES="${LOADED_MODULES} ${x}"
