Added support for reading /mnt/cdrom/cdupdate.sh if its executable on the livecd
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@191 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -486,6 +486,16 @@ else
 	mkdir -p /newroot/tmp/.initrd
 fi
 
+if [ -x /newroot/mnt/cdrom/cdupdate.sh ]
+then
+    /newroot/mnt/cdrom/cdupdate.sh
+    if [ "$?" != '0' ]
+    then
+	echo "FAILED TO EXECUTE cdupdate.sh"
+	/bin/ash
+    fi
+fi
+
 if [ "$0" = '/linuxrc' ]
 then
 	[ ! -e /newroot/dev/console ] && mknod /newroot/dev/console c 5 1
