Udev speedups; thanks to Eric Edgar for the patch - bug #72253.
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@150 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -147,6 +147,7 @@ then
 	then
 		cd /sys
 		kill_devfsd
+		echo -e "${GOOD}>>${NORMAL}${BOLD} Activating udev...${NORMAL}"
 		runUdev
 		mv /dev/* /newroot/dev
 	else
@@ -214,6 +215,7 @@ if [ "${USE_UDEV_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
 then
 	USE_DEVFS_NORMAL=0
 	cd /sys
+	echo -e "${GOOD}>>${NORMAL}${BOLD} Activating udev...${NORMAL}"
 	runUdev
 elif [ "${CDROOT}" -eq '0' -a "${USE_DEVFS_NORMAL}" -eq '1' ]
 then
@@ -419,6 +421,12 @@ then
 	rm /tmp/.initrd/dev -rf || '*: Failed to remove the initrd /dev!'
 elif [ "${USE_UDEV_NORMAL}" -eq '1' ]
 then
+	rm /tmp/.initrd/dev/fd || echo '*: Failed to rm the initrd fd!'
+	rm /tmp/.initrd/dev/stdin || echo '*: Failed to rm the initrd stdin!'
+	rm /tmp/.initrd/dev/stdout || echo '*: Failed to rm the initrd stdout!'
+	rm /tmp/.initrd/dev/stderr || echo '*: Failed to rm the initrd stderr!'
+	rm /tmp/.initrd/dev/core || echo '*: Failed to rm the initrd core!'
+	umount /tmp/.initrd/dev || echo '*: Failed to unmount the initrd /dev!'
 	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
 	umount /tmp/.initrd/sys || echo '*: Failed to unmount the initrd /sys!'
 elif [ "${CDROOT}" -eq '1' ]
