Add missing echo; #77363.
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@160 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -441,7 +441,7 @@ if [ "${USE_DEVFS_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
 then
 	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
 	mount -n --move /tmp/.initrd/dev dev || echo '*: Failed to move over the /dev tree!'
-	rm -rf /tmp/.initrd/dev || '*: Failed to remove the initrd /dev!'
+	rm -rf /tmp/.initrd/dev || echo '*: Failed to remove the initrd /dev!'
 elif [ "${USE_UDEV_NORMAL}" -eq '1' ]
 then
 	rm /tmp/.initrd/dev/fd || echo '*: Failed to rm the initrd fd!'
@@ -457,7 +457,7 @@ then
 	umount /tmp/.initrd/proc || echo "*: Failed to unmount the initrd /proc!"
 	umount /dev 2>/dev/null
 	mount -n --move /tmp/.initrd/dev dev 2>/dev/null
-	rm -rf /tmp/.initrd/dev || '*: Failed to remove the initrd /dev!'
+	rm -rf /tmp/.initrd/dev || echo '*: Failed to remove the initrd /dev!'
 
 	umount /sys 2>/dev/null
 	umount /tmp/.initrd/sys 2>/dev/null
