>> 3.0.2e. Code formatting fixes from Bob Barry, as well as a patch for bug #57953 from Martin Parm. Udev support, bug #49328.
git-svn-id: svn+ssh://svn.gentoo.org/var/svnroot/genkernel/trunk@119 67a159dc-881f-0410-a524-ba9dfbe2cb84

diff --git a/generic/linuxrc b/generic/linuxrc
--- a/generic/linuxrc
+++ b/generic/linuxrc
@@ -7,6 +7,7 @@
 . /etc/initrd.scripts
 
 USE_DEVFS_NORMAL=1
+USE_UDEV_NORMAL=2
 
 if [ "$$" != '1' ]
 then
@@ -38,6 +39,12 @@ do
 		;;
 		nodevfs)
 			USE_DEVFS_NORMAL=0
+		;;
+		udev)
+			USE_UDEV_NORMAL=1
+		;;
+		noudev)
+			USE_UDEV_NORMAL=0
 		;;
 		loop\=*)
 			LOOP=`parse_opt "${x}"`
@@ -139,8 +146,54 @@ then
 	fi
 fi
 
+# Disable udev support if /dev is already mounted as devfs
+[ -e /dev/.devfsd ] && USE_UDEV_NORMAL=0
+
+# If using 2.4 and udev; back off...
+[ "${KMAJOR}" -eq 2 -a "${KMINOR}" -lt '6' -a "${USE_UDEV_NORMAL}" -eq 1 ] &&
+	USE_UDEV_NORMAL=0
+
+# Try to mount sysfs, and if it fails, do not use udev
+if [ "${USE_UDEV_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
+then
+	mount -t sysfs sys /sys 2> /dev/null
+	[ "$?" -eq "0" ] || USE_UDEV_NORMAL=0
+fi
+
+# Check udev is on...
+[ "${KMAJOR}" -ge 2 ] && USE_UDEV_SUPPORT=1
+[ "${KMAJOR}" -eq 2 -a "${KMINOR}" -ge '6' ] && USE_UDEV_SUPPORT=1
+[ "${USE_UDEV_SUPPORT}" -eq '1' -a -f /sbin/udev -a "${USE_UDEV_NORMAL}" -ne 0 ] && USE_UDEV_NORMAL=1
+
 # Don't do else b/c we set CDROOT=0 if it fails to detect
-if [ "${CDROOT}" -eq '0' -a "${USE_DEVFS_NORMAL}" -eq '1' ]
+if [ "${USE_UDEV_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
+then
+	export ACTION=add
+	export UDEV_NO_SLEEP=1
+
+	# Add block devices and their partitions to /dev,
+	# using information from /sys, and only those
+	# devices (since other are not needed for boot).
+
+	cd /sys
+	for x in block/*
+	do
+		export DEVPATH="/${x}"
+		/sbin/udev block
+
+		for y in ${x}/*
+		do
+			if [ -f "${y}/dev" ]
+			then
+				export DEVPATH="/${y}"
+				/sbin/udev block
+			fi
+		done
+	done
+	cd /
+
+	unset -v ACTION DEVPATH UDEV_NO_SLEEP
+elif [ "${CDROOT}" -eq '0' -a "${USE_DEVFS_NORMAL}" -eq '1' ]
 then
 	[ ! -e /dev/.devfsd ] && mount -t devfs devfs /dev
 	devfsd /dev -np
@@ -324,6 +377,7 @@ fi
 echo -ne "${GOOD}>>${NORMAL}${BOLD} Booting"
 
 cd /newroot
+mkdir /newroot/proc /newroot/sys 2>/dev/null
 pivot_root . tmp/.initrd
 echo -n '.'
 
@@ -332,6 +386,10 @@ then
 	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
 	mount -n --move /tmp/.initrd/dev dev || echo '*: Failed to move over the /dev tree!'
 	rm /tmp/.initrd/dev -rf || '*: Failed to remove the initrd /dev!'
+elif [ "${USE_UDEV_NORMAL}" -eq '1' -a "${CDROOT}" -eq '0' ]
+then
+	umount /tmp/.initrd/proc || echo '*: Failed to unmount the initrd /proc!'
+	umount /tmp/.initrd/sys || echo '*: Failed to unmount the initrd /sys!'
 elif [ "${CDROOT}" -eq '1' ]
 then
 	# If automount at boot was on with devfs, we'll want to umount it
